name: "Build Docker image"

on:
  workflow_call:
    secrets:
      DOCKER_LOGIN:
        required: true
      DOCKER_PASSWORD:
        required: true
  workflow_dispatch:

env:
  MASTER_BRANCH: master
  BRANCH_NAME: ${{github.head_ref || github.ref_name}}
  DOCKER_REPOSITORY: foxleren/onyxdb-agent

jobs:
  build-push-docker-image:
    runs-on: onyxdb-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH_NAME}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_LOGIN}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t ${{env.DOCKER_REPOSITORY}} -f Dockerfile .

      - name: Tag Docker image
        run: |
          BRANCH_IMAGE = ${{env.DOCKER_REPOSITORY}}:${{env.BRANCH_NAME}}-${GITHUB_SHA::7}
          echo "::notice::Pushing image $BRANCH_IMAGE"
          docker tag ${{env.DOCKER_REPOSITORY}} $BRANCH_IMAGE
          if [ ${{env.BRANCH_NAME}} == ${{env.MASTER_BRANCH}} ]; then
            docker tag  ${{env.DOCKER_REPOSITORY}} ${{env.DOCKER_REPOSITORY}}:latest
          fi

      - name: Push Docker image
        run: |
          docker push ${{env.DOCKER_REPOSITORY}}:${{env.BRANCH_NAME}}-${GITHUB_SHA::7}
          if [ ${{env.BRANCH_NAME}} == ${{env.MASTER_BRANCH}} ]; then
            docker push ${{env.DOCKER_REPOSITORY}}:latest
          fi
